version: '2'

services:

  proxy:
    build: .
    restart: unless-stopped
    environment:
     - DOMAIN=clevergreg2.localtunnel.me
     - SKIP_DOMAIN_VALIDATION=true
     - SUB_DOMAINS=test,plop
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - tls-proxy:/etc/letsencrypt

volumes:
  tls-proxy:
    driver: local
