FROM          software-factory.clevertoday.xyz/clever-nginx:latest
MAINTAINER    Grégoire Weber <gregoire@clevertoday.com>

COPY          nginx.conf  /etc/nginx/nginx.conf
COPY          index.html  /usr/share/nginx/