FROM          software-factory.clevertoday.xyz/clever-nginx:lastest
MAINTAINER    Grégoire Weber <gregoire@clevertoday.com>

COPY          nginx.conf.template   /etc/nginx/nginx.conf.template
COPY          index.html            /usr/share/nginx/